// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uezaxspgkwttrowpnfxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlemF4c3Bna3d0dHJvd3BuZnhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NjI2NjYsImV4cCI6MjA2MzMzODY2Nn0.KY6zBhHpGZ07GYo_pcP4ZdCUxrermYc6t9gFaq7isxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);